SELECT P.PRODUCT_CODE, (P.PRICE*OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P INNER JOIN(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
                         FROM OFFLINE_SALE
                         GROUP BY PRODUCT_ID) OS ON P.PRODUCT_ID = OS.PRODUCT_ID
                         ORDER BY SALES DESC, PRODUCT_CODE